name: Daily Crime Data Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering
    inputs:
      debug:
        description: 'Enable debug mode'
        required: false
        default: false
        type: boolean

permissions:
  contents: write  # Allow pushing scraped data back to repo

jobs:
  scrape-crime-data:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for proper git operations
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm
          
      - name: Run crime data scraper
        run: |
          python main.py --mode full
        env:
          DEBUG_MODE: ${{ github.event.inputs.debug || 'false' }}
          
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "🔄 Daily crime data update - $(date +'%Y-%m-%d %H:%M:%S UTC')"
          git push
